=== mocno/turing_machine/tm-configuration-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "./tm-configuration-schema.json",

  "title": "TM-Configuration",
  "description": "Turing Machine Configuration",
  "type": "object",

  "properties": {
    "type": {
      "default": "tape",
      "enum": ["tape", "2d"],
      "title": "Type of machine"
    },
    "start-state": {
      "title": "Initial state of the machine",
      "type": "string"
    },
    "blank-symbol": {
      "title": "Empty character of the tape",
      "type": "string",
      "minLength": 1,
      "maxLength": 1
    },
    "states": {
      "type": "object",
      "title": "Transition function",
      "description": "The rules of the machine to move and edit",
      "patternProperties": {
        "": {
          "type": "object",
          "patternProperties": {
            "": {
              "type": ["string", "array"],
              "items": {
                "type": "string"
              },
              "minItems": 2,
              "maxItems": 3,
              "minLength": 1,
              "maxLength": 1
            }
          }
        }
      },
      "minProperties": 1
    },
    "inputs": {
      "type": "array",
      "title": "Input tapes to the machine",
      "items": {
        "type": "object",
        "properties": {
          "tape": {
            "type": ["string", "array"],
            "items": {
              "type": "string"
            }
          },
          "position": {
            "type": ["integer", "array"],
            "items": {
              "type": "integer"
            },
            "minItems": 2,
            "maxItems": 2
          }
        },
        "required": ["tape"]
      },
      "minItems": 1
    }
  },
  "required": ["start-state", "states", "inputs"]
}

=== mocno/turing_machine/examples/2d-ping-pong.json
{
    "type": "2d",
    "start-state": "go(DR,verify=DR)",
    "blank-symbol": " ",

    "states": {
        "go(UR,verify=UR)": {
            " o": ["R", "test(R,d=UR,verify=U)", "o"],
            "x": ["D", "go(DR,verify=DR)"]
        },
        "go(DR,verify=DR)": {
            " o": ["R", "test(R,d=DR,verify=D)", "o"],
            "x": ["U", "go(UR,verify=UR)"]
        },
        "go(UL,verify=UL)": {
            " o": ["L", "test(L,d=UL,verify=U)", "o"],
            "x": ["D", "go(DL,verify=DL)"]
        },
        "go(DL,verify=DL)": {
            " o": ["L", "test(L,d=DL,verify=D)", "o"],
            "x": ["U", "go(UL,verify=UL)"]
        },

        "go(UR,verify=U)": {
            "o": ["U", "test(U,d=UR)"]
        },
        "go(DR,verify=D)": {
            "o": ["D", "test(D,d=DR)"]
        },
        "go(UL,verify=U)": {
            "o": ["U", "test(U,d=UL)"]
        },
        "go(DL,verify=D)": {
            "o": ["D", "test(D,d=DL)"]
        },

        "go(UR)": {
            "o": ["R", "go(U,d=UR)", " "]
        },
        "go(DR)": {
            "o": ["R", "go(D,d=DR)", " "]
        },
        "go(UL)": {
            "o": ["L", "go(U,d=UL)", " "]
        },
        "go(DL)": {
            "o": ["L", "go(D,d=DL)", " "]
        },

        "go(U,d=UR)": {
            " ": ["U", "go(UR,verify=UR)"]
        },
        "go(D,d=DR)": {
            " ": ["D", "go(DR,verify=DR)"]
        },
        "go(U,d=UL)": {
            " ": ["U", "go(UL,verify=UL)"]
        },
        "go(D,d=DL)": {
            " ": ["D", "go(DL,verify=DL)"]
        },

        "test(R,d=UR,verify=U)": {
            "x": ["L", "go(UL,verify=UL)"],
            " ": ["L", "go(UR,verify=U)"]
        },
        "test(R,d=DR,verify=D)": {
            "x": ["L", "go(DL,verify=DL)"],
            " ": ["L", "go(DR,verify=D)"]
        },
        "test(L,d=DL,verify=D)": {
            "x": ["R", "go(DR,verify=DR)"],
            " ": ["R", "go(DL,verify=D)"]
        },
        "test(L,d=UL,verify=U)": {
            "x": ["R", "go(UR,verify=UR)"],
            " ": ["R", "go(UL,verify=U)"]
        },

        "test(U,d=UR)": {
            "x": ["D", "go(DR,verify=DR)"],
            " ": ["D", "go(UR)"]
        },
        "test(D,d=DR)": {
            "x": ["U", "go(UR,verify=UR)"],
            " ": ["U", "go(DR)"]
        },
        "test(U,d=UL)": {
            "x": ["D", "go(DL,verify=DL)"],
            " ": ["D", "go(UL)"]
        },
        "test(D,d=DL)": {
            "x": ["U", "go(UL,verify=UL)"],
            " ": ["U", "go(DL)"]
        }
    },

    "inputs": [
        {
            "tape": [
                "xxxxx",
                "x   x",
                "x   x",
                "x   x",
                "x   x",
                "xxxxx"
            ],
            "position": [2, 2]
        },
        {
            "tape": [
                "xxxxxxxxxxxxxxxx",
                "x         x    x",
                "x         x    x",
                "x         x    x",
                "x   x          x",
                "x   x          x",
                "xxxxxxxxxxxxxxxx"
            ],
            "position": [2, 2]
        },
        {
            "tape": [
                "xxxxxxxxxxxxxxxx",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "x              x",
                "xxxxxxxxxxxxxxxx"
            ],
            "position": [5, 5]
        }
    ]
}

=== mocno/turing_machine/examples/2d_loading.json
{
    "type": "2d",
    "start-state": "step1",
    "blank-symbol": " ",

    "states": {
        "step1": {
            " ": ["R", "step2", "."],
            ".": ["R", "step2", " "]
        },
        "step2": {
            " ": ["D", "step3", "."],
            ".": ["D", "step3", " "]
        },
        "step3": {
            " ": ["L", "step4", "."],
            ".": ["L", "step4", " "]
        },
        "step4": {
            " ": ["U", "step1", "."],
            ".": ["U", "step1", " "]
        }
    },

    "inputs": [
        {
            "tape": [
                " .",
                ". "
            ]
        }
    ]
}

=== mocno/turing_machine/examples/2d-worm-knowing-another-dimension.json
{
    "type": "2d",
    "start-state": "go(R)",
    "blank-symbol": " ",

    "states": {
        "go(R)": {
            ".": ["R", "go(D)", " "],
            " ": ["R", "go(D)", "."]
        },
        "go(D)": {
            ".": ["D", "go(R)", " "],
            " ": ["D", "go(R)", "."]
        }
    },

    "inputs": [
        {
            "tape": []
        }
    ]
}
